import { ThemeProp } from "react-native-paper/lib/typescript/types";
import { MD3Colors, MD3DarkTheme, MD3LightTheme, useTheme } from "react-native-paper";

export const lightTheme = {
    ...MD3LightTheme,
    colors: {
        ...MD3LightTheme.colors,
        primary: "#8F4C38",
        "surfaceTint": "#8F4C38",
        "onPrimary": "#FFFFFF",
        "primaryContainer": "#FFDBD1",
        "onPrimaryContainer": "#3A0B01",
        "secondary": "#0D6B58",
        "onSecondary": "#FFFFFF",
        "secondaryContainer": "#A1F2DA",
        "onSecondaryContainer": "#002019",
        "tertiary": "#8D4A5B",
        "onTertiary": "#FFFFFF",
        "tertiaryContainer": "#FFD9E0",
        "onTertiaryContainer": "#3A0719",
        "error": "#8F4A50",
        "onError": "#FFFFFF",
        "errorContainer": "#FFDADB",
        "onErrorContainer": "#3B0811",
        "background": "#FFF8F6",
        "onBackground": "#231917",
        "surface": "#FFF8F6",
        "onSurface": "#231917",
        "surfaceVariant": "#F5DED8",
        "onSurfaceVariant": "#53433F",
        "outline": "#85736E",
        "outlineVariant": "#D8C2BC",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#392E2B",
        "inverseOnSurface": "#FFEDE8",
        "inversePrimary": "#FFB5A0",
        "primaryFixed": "#FFDBD1",
        "onPrimaryFixed": "#3A0B01",
        "primaryFixedDim": "#FFB5A0",
        "onPrimaryFixedVariant": "#723523",
        "secondaryFixed": "#A1F2DA",
        "onSecondaryFixed": "#002019",
        "secondaryFixedDim": "#86D6BF",
        "onSecondaryFixedVariant": "#005142",
        "tertiaryFixed": "#FFD9E0",
        "onTertiaryFixed": "#3A0719",
        "tertiaryFixedDim": "#FFB1C2",
        "onTertiaryFixedVariant": "#713343",
        "surfaceDim": "#E8D6D2",
        "surfaceBright": "#FFF8F6",
        "surfaceContainerLowest": "#FFFFFF",
        "surfaceContainerLow": "#FFF1ED",
        "surfaceContainer": "#FCEAE5",
        "surfaceContainerHigh": "#F7E4E0",
        "surfaceContainerHighest": "#F1DFDA"
    }
}

export const darkTheme = {
    ...MD3DarkTheme,
    colors: {
        ...MD3DarkTheme.colors,
        "primary": "#FFB5A0",
        "surfaceTint": "#FFB5A0",
        "onPrimary": "#561F0F",
        "primaryContainer": "#723523",
        "onPrimaryContainer": "#FFDBD1",
        "secondary": "#86D6BF",
        "onSecondary": "#00382D",
        "secondaryContainer": "#005142",
        "onSecondaryContainer": "#A1F2DA",
        "tertiary": "#FFB1C2",
        "onTertiary": "#551D2D",
        "tertiaryContainer": "#713343",
        "onTertiaryContainer": "#FFD9E0",
        "error": "#FFB2B7",
        "onError": "#561D24",
        "errorContainer": "#72333A",
        "onErrorContainer": "#FFDADB",
        "background": "#1A110F",
        "onBackground": "#F1DFDA",
        "surface": "#1A110F",
        "onSurface": "#F1DFDA",
        "surfaceVariant": "#53433F",
        "onSurfaceVariant": "#D8C2BC",
        "outline": "#A08C87",
        "outlineVariant": "#53433F",
        "shadow": "#000000",
        "scrim": "#000000",
        "inverseSurface": "#F1DFDA",
        "inverseOnSurface": "#392E2B",
        "inversePrimary": "#8F4C38",
        "primaryFixed": "#FFDBD1",
        "onPrimaryFixed": "#3A0B01",
        "primaryFixedDim": "#FFB5A0",
        "onPrimaryFixedVariant": "#723523",
        "secondaryFixed": "#A1F2DA",
        "onSecondaryFixed": "#002019",
        "secondaryFixedDim": "#86D6BF",
        "onSecondaryFixedVariant": "#005142",
        "tertiaryFixed": "#FFD9E0",
        "onTertiaryFixed": "#3A0719",
        "tertiaryFixedDim": "#FFB1C2",
        "onTertiaryFixedVariant": "#713343",
        "surfaceDim": "#1A110F",
        "surfaceBright": "#423734",
        "surfaceContainerLowest": "#140C0A",
        "surfaceContainerLow": "#231917",
        "surfaceContainer": "#271D1B",
        "surfaceContainerHigh": "#322825",
        "surfaceContainerHighest": "#3D322F"
    }
}

export type AppTheme = typeof lightTheme;
export const useAppTheme = () => useTheme<AppTheme>();